server:
  port: 9001

spring:
  application:
    name: super-cloud-gateway
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.42.89.195:3306/cloud_video?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 101.42.89.195:8848
  gateway:
    routes: #数组形式
      - id: super-cloud-system  #路由唯一标识
        #uri: http://127.0.0.1:8000  #想要转发到的地址
        uri: lb://super-cloud-system  # 从nacos获取名称转发,lb是负载均衡轮训策略
  predicates: #断言 配置哪个路径才转发
    - Path=/super-cloud-system/**
  filters: #过滤器，请求在传递过程中通过过滤器修改
    - StripPrefix=1 #去掉第一层前缀
  discovery:
    locator:
      enabled: true  #开启网关拉取nacos的服务

mybatis-plus:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.slhc.basics.core;
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除配置
      logic-delete-value: -1
      logic-not-delete-value: 0