server:
  port: 9002

spring:
  redis:
    host: 127.0.0.1
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER #springboot2.6.x如果不加该配置会报错
  application:
    name: super-cloud-oauth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/super_cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: '!QAZxsw2'
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
mybatis-plus:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.superCloud.web.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除配置
      logic-delete-value: -1
      logic-not-delete-value: 0

springfox:
  documentation:
    swagger-ui:
      enabled: true